// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AccordionController from "./accordion_controller.ts"
application.register("accordion", AccordionController)

import BodyExaminationsTableController from "./body_examinations_table_controller.js"
application.register("body-examinations-table", BodyExaminationsTableController)

import CacheController from "./cache_controller.ts"
application.register("cache", CacheController)

import ConfirmController from "./confirm_controller.js"
application.register("confirm", ConfirmController)

import HelloController from "./hello_controller.js"
application.register("hello", HelloController)

import HistoryController from "./history_controller.ts"
application.register("history", HistoryController)

import LocalstorageController from "./localstorage_controller.ts"
application.register("localstorage", LocalstorageController)

import ModalController from "./modal_controller.ts"
application.register("modal", ModalController)

import NestedFormController from "./nested_form_controller.ts"
application.register("nested-form", NestedFormController)

import PatientStepsController from "./patient_steps_controller.ts"
application.register("patient-steps", PatientStepsController)

import PreviewController from "./preview_controller.ts"
application.register("preview", PreviewController)

import ReactController from "./react_controller.jsx"
application.register("react", ReactController)

import UnlockController from "./unlock_controller.js"
application.register("unlock", UnlockController)

import UploadController from "./upload_controller.ts"
application.register("upload", UploadController)
